name: CMake on a single platform


on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  MY_VARIABLE: "Hello"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print environment variable
      run: echo ${{ env.MY_VARIABLE }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build via CMake
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: List all files
      run: ls -laR ${{ github.workspace }}/build

    - name: Run main program
      run: ${{ github.workspace }}/build/MyProgram

    - name: Run tests via CTest
      run: ctest --test-dir ${{ github.workspace }}/build --output-on-failure

